### ISSUE TITLE
Got error "no function clause matching in Phoenix.HTML.Form.input_value/2"

### ISSUE THREAD

**Issue by dgamidov** [phoenixframework/phoenix_html#140]
Hello!

After updating phoenix_html from 2.8.0 to 2.9.2 I got "no function clause matching in Phoenix.HTML.Form.input_value/2" for my checkbox (I used string as a field):

```
iex(21)> Phoenix.HTML.Form.checkbox(:checkbox, "1", value: true)
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_value/2
    (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.input_value(:checkbox, "1")
    (phoenix_html) lib/phoenix_html/form.ex:699: Phoenix.HTML.Form.checkbox/3
```

Integer does not work, too:

```
iex(21)> Phoenix.HTML.Form.checkbox(:checkbox, 1, value: true)
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_value/2
    (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.input_value(:checkbox, 1)
    (phoenix_html) lib/phoenix_html/form.ex:699: Phoenix.HTML.Form.checkbox/3
```

Atom works fine:

```
iex(21)> Phoenix.HTML.Form.checkbox(:checkbox, :test, value: true)
{:safe,
 [[60, "input",
   [[32, "name", 61, 34, "checkbox[test]", 34],
    [32, "type", 61, 34, "hidden", 34], [32, "value", 61, 34, "false", 34]],
   62],
  [60, "input",
   [[32, "checked", 61, 34, "checked", 34],
    [32, "id", 61, 34, "checkbox_test", 34],
    [32, "name", 61, 34, "checkbox[test]", 34],
    [32, "type", 61, 34, "checkbox", 34], [32, "value", 61, 34, "true", 34]],
   62]]}
```

I have checked function Phoenix.HTML.Form.input_value/2:

```
iex(19)> Phoenix.HTML.Form.input_value(:test, :"1")
nil

iex(20)> Phoenix.HTML.Form.input_value(:test, 1)
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_value/2
    (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.input_value(:test, 1)

iex(20)> Phoenix.HTML.Form.input_value(:test, "1")
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_value/2
    (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.input_value(:test, "1")
```

A have found that in commit [Always look up for parameters in select](https://github.com/phoenixframework/phoenix_html/commit/b0ff9f2508d8e95ddc95e61ba9a25b292b12f2db) there was a change:
from: `def input_value(%{source: source, impl: impl} = form, field, default) do`
to___: `def input_value(%{source: source, impl: impl} = form, field) when is_atom(field)
`

Is it an issue, or I should use atom as field?

Thanks!
Denis.

**Comment by josevalim** [comment]
Can you please explain what you are trying to achieve? Your invocation syntax for checkbox is wrong, the second argument must be a field name. Were you on purpose trying to give it a name of "0"? If so, I am more inclined to say that an atom needs to be given indeed.

**Comment by dgamidov** [comment]
Thank you for fast answer, Jose!

There is list_of_values preloaded from database.

```
iex(1)> list_of_values = [{"first item", 1}, {"second item", 2}]
[{"first item", 1}, {"second item", 2}]
```

Than I need to have checkboxes for every row.
I use it for multiple checkbox generation in Phoenix:
```
<%= for {name, id} <- @list_of_values do %>
  <div>
    <%= checkbox :checked_list, id, value: name %> <%= name %>
  </div>
<%= end %>
```

```
iex(2)> for {name, id} <- list_of_values, do: Phoenix.HTML.Form.checkbox(:checked_list, id, value: name)
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_value/2
    (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.input_value(:checked_list, 1)
    (phoenix_html) lib/phoenix_html/form.ex:699: Phoenix.HTML.Form.checkbox/3
          (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
          (stdlib) erl_eval.erl:228: :erl_eval.expr/5
          (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by josevalim** [comment]
We can probably remove the `is_atom(field)` [check from here](https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L302) and add a test case. Can you please send a PR?

**Comment by dgamidov** [comment]
Sure.
Thank you for support!
