### ISSUE TITLE
ArgumentError when using date_select in form_tag

### ISSUE THREAD

**Issue by philippneugebauer** [phoenixframework/phoenix_html#225]
I'm getting the following error when using a `date(time)_select` in a [`form_for @conn`](https://github.com/philippneugebauer/phoenix_html_date_select_error/blob/master/lib/date_select_error_web/templates/search/index.html.eex) while all other used form elements work:

```
[error] #PID<0.385.0> running DateSelectErrorWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (phoenix_html) lib/phoenix_html/form.ex:1415: Phoenix.HTML.Form.datetime_options/7
        (phoenix_html) lib/phoenix_html/form.ex:1381: anonymous fn/7 in Phoenix.HTML.Form.datetime_builder/5
        (phoenix_html) lib/phoenix_html/form.ex:1290: Phoenix.HTML.Form.date_builder/2
        (date_select_error) lib/date_select_error_web/templates/search/index.html.eex:6: anonymous fn/1 in DateSelectErrorWeb.SearchView."index.html"/1
        (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.form_for/4
        (date_select_error) lib/date_select_error_web/templates/search/index.html.eex:1: DateSelectErrorWeb.SearchView."index.html"/1
        (date_select_error) lib/date_select_error_web/templates/layout/app.html.eex:29: DateSelectErrorWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (date_select_error) lib/date_select_error_web/controllers/search_controller.ex:1: DateSelectErrorWeb.SearchController.action/2
        (date_select_error) lib/date_select_error_web/controllers/search_controller.ex:1: DateSelectErrorWeb.SearchController.phoenix_controller_pipeline/2
        (date_select_error) lib/date_select_error_web/endpoint.ex:1: DateSelectErrorWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (date_select_error) lib/date_select_error_web/endpoint.ex:1: DateSelectErrorWeb.Endpoint.plug_builder_call/2
        (date_select_error) lib/plug/debugger.ex:122: DateSelectErrorWeb.Endpoint."call (overridable 3)"/2
        (date_select_error) lib/date_select_error_web/endpoint.ex:1: DateSelectErrorWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/ppn/ppn/date_select_error/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

I was also able to reproduce the error in a fresh phoenix application:
https://github.com/philippneugebauer/phoenix_html_date_select_error
You just need to call `localhost:4000` and you will get the error.

**Comment by josevalim** [comment]
This is already fixed in master, I will do a new release. :)
