### ISSUE TITLE
Can't use `checked` attribute inside `<input .. >` tag

### ISSUE THREAD

**Issue by alaadahmed** [phoenixframework/phoenix_html#389]
__Phoenix__: `1.6.12`
__LiveView__: `0.18.1`
__Phoenix.HTM__: `3.2`

I am trying to use `checked` attribute inside `<input type="radio" ../>` tag, but it throw error of 
```
protocol Enumerable not implemented for "checked" of type BitString. ....
```
I found out I must pass attributes in form of `key="value"` but this attribute usually passed alone!
In my case I use it inside live_view render function in `~H` and I use a function `checked?(current, new, "checked")` to determine if this `<input type="radio" ../>` is checked or no!

To solve this issue, I must write the function so that it will pass a _list_ -> `checked?(current, new, [checked: true])`! But this is not comply with HTML input tag, because now it will be like this `<input type="radio" ... checked="" />`

Maybe we can account for such cases in the `Phoenix.HTML.buid_attrs` for such type of single attributes?! 

```
 defp build_attrs(attr) when attr in ["checked", "readonly"], do: attr

# or if it must be list then
defp build_attrs([attr]) when attr in ["checked", "readonly"], do: attr
```

**Comment by josevalim** [comment]
Sorry, it is not clear what is happening. Can you please show exactly how you are calling the function? And if there is an exception, please include full error message and stactrace.

**Comment by alaadahmed** [comment]
In live component this is render function:
```
~H"""
      <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <%= for status <- ~w/ANY APPROVED PENDING/ do %>
          <label class={"btn btn-warning #{set_flag(status, @status)}"}>
            <input id={"search_status_#{status}"}
                name="search[status]"
                type="radio"
                phx-click="filter-status-changed"
                phx-value-id={status}
                phx-target={@myself}
                value={status}
                autocomplete="off"
                {set_flag(status, @status, "checked")}>   <<<<<<<<<<<<<<<<<<<<<<<
            <%= status %>
          </label>
        <% end %>
      </div>
    """
```

The function used to determine if `radio` button is checked or no
```
defp set_flag(current, new, flag \\ "active")
defp set_flag(current, new, flag), do: if(checked_if_status(current, new), do: flag, else: "")
```

The error message:
```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for "" of type BitString. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, SFTPClient.Stream, Stream, Timex.Interval
        (elixir 1.13.2) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.13.2) lib/enum.ex:143: Enumerable.reduce/3
        (elixir 1.13.2) lib/enum.ex:4144: Enum.reverse/1
        (elixir 1.13.2) lib/enum.ex:3491: Enum.to_list/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:212: Phoenix.HTML.attributes_escape/1
        (catalog2 0.1.0) lib/catalog2_web/live/product_live/product_filter_by_status.ex:12: anonymous fn/3 in Catalog2Web.ProductLive.ProductFilterByStatus.render/1
        (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (catalog2 0.1.0) lib/catalog2_web/live/product_live/product_filter_by_status.ex:10: anonymous fn/2 in Catalog2Web.ProductLive.ProductFilterByStatus.render/1
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/diff.ex:691: Phoenix.LiveView.Diff.render_component/9
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/diff.ex:636: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 3.17) maps.erl:410: :maps.fold_1/3
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/diff.ex:609: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/diff.ex:145: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/static.ex:244: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/static.ex:127: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.18.1) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.6.12) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
        (catalog2 0.1.0) lib/catalog2_web/endpoint.ex:1: Catalog2Web.Endpoint.plug_builder_call/2
```

**Comment by alaadahmed** [comment]
To fix this issue I make these changes:
```
 <input id={"search_status_#{status}"}
                name="search[status]"
                type="radio"
                phx-click="filter-status-changed"
                phx-value-id={status}
                phx-target={@myself}
                value={status}
                autocomplete="off"
                {set_flag(status, @status, [checked: true])}> <<<<<<<<<<<<<<<<<<<
```
and
```
defp set_flag(current, new, flag), do: if(checked_if_status(current, new), do: flag, else: [])
```
and the output html will be:
```
<label class="btn btn-warning active">
        <input id="search_status_APPROVED" name="search[status]" type="radio" phx-click="filter-status-changed" 
                   phx-value-id="APPROVED" 
                   phx-target="1" 
                   value="APPROVED" 
                   autocomplete="off" 
                   checked=""> <<<<<<<<<<<<<<<<<
        APPROVED
</label>
```

**Comment by chrismccord** [comment]
the splat form of heex `<input {...} />` only accepts a keyword list or map of attributes, but your first sample was passing only "checked", which is not an enum, so this is all working as intended. Thanks!
