### ISSUE TITLE
attributes_escape/1 does not escape ids completely

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_html#450]
I have data from a legacy system. On a few entries in noticed a subtle breakage. I traced it down to attributes_escape/1 not escaping ids sufficiently-

The docs hint that passing a number will throw an error:
```
iex(8)> attributes_escape(%{id: 11})
** (ArgumentError) attempting to set id attribute to 11, but setting the DOM ID to a number can lead to unpredictable behaviour. Instead consider prefixing the id with a string, such as "user-11" or similar
    (phoenix_html 4.1.1) lib/phoenix_html.ex:258: Phoenix.HTML.id_value/1
    (phoenix_html 4.1.1) lib/phoenix_html.ex:208: Phoenix.HTML.build_attrs/1
    (phoenix_html 4.1.1) lib/phoenix_html.ex:195: Phoenix.HTML.attributes_escape/1
    iex:8: (file)
```

But passing the number a string will happily produce output:
```
iex(7)> attributes_escape(%{id: "11"})
{:safe, [" id=\"", "11", 34]}
```

Same for whitespace ("An ID attribute's value must not contain [ASCII whitespace](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace#in_html) characters.")
```
iex(8)> attributes_escape(%{id: "white space"})
{:safe, [" id=\"", "white space", 34]}
```

Additionally also characters like "/" are not valid in ids, but the escape function will not escape them as well:
```
iex(4)> attributes_escape(%{id: "asdflkj//sdf"})
{:safe, [" id=\"", "asdflkj//sdf", 34]}
```

> Technically, the value for an ID attribute may contain any other Unicode character. However, when used in CSS selectors, either from JavaScript using APIs like [Document.querySelector()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) or in CSS stylesheets, ID attribute values must be valid [CSS identifiers](https://developer.mozilla.org/en-US/docs/Web/CSS/ident). This means that if an ID attribute value is not a valid CSS identifier (for example, my?id or 1234) then it must be escaped before being used in a selector, either using the [CSS.escape()](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape_static) method or [manually](https://developer.mozilla.org/en-US/docs/Web/CSS/ident#escaping_characters).

**Comment by SteffenDE** [comment]
I think we need to differentiate between what's allowed in attributes vs. what's allowed to be a valid CSS selector. The only official restriction on IDs in HTML5 is no whitespaces, so this is something we could warn about when we encounter one, but the additional overhead of checking strings for whitespaces might not be worth it.

Having a `css_escape` function would be useful though - I created an issue for this in Floki a while back: https://github.com/philss/floki/issues/554

> On a few entries in noticed a subtle breakage.

Can you provide some details? If this is on the JS side, adding a `CSS.escape` might already be enough.

**Comment by josevalim** [comment]
The goal of this library is to escape HTML to avoid HTML injection, that's it. Doing per attribute validation would be quite hard because some attributes also depend on the tag. In the case of ID, we do validate integers to avoid common pitfalls (and because it is very cheap to do so!), but it is not our goal or intention to validate all of it.

**Comment by ponychicken** [comment]
> I think we need to differentiate between what's allowed in attributes vs. what's allowed to be a valid CSS selector. The only official restriction on IDs in HTML5 is no whitespaces, so this is something we could warn about when we encounter one, but the additional overhead of checking strings for whitespaces might not be worth it.
> 
> Having a `css_escape` function would be useful though - I created an issue for this in Floki a while back: [philss/floki#554](https://github.com/philss/floki/issues/554)
> 
> > On a few entries in noticed a subtle breakage.
> 
> Can you provide some details? If this is on the JS side, adding a `CSS.escape` might already be enough.

The problem is that if there is one element in the HEEX with an invalid id and this element has a `phx-click` attribute, the built in javascript will try to do  `document.querySelectorAll(invalidId)` and fail, and since the error is not caught, no click handlers will be installed at all. eg one inavlid id ==> no javascript clicks at all.

**Comment by SteffenDE** [comment]
That's something we are able to fix in LV's js though, right? So more of a LV bug then.
