### ISSUE TITLE
no function clause matching in Phoenix.HTML.Form.normalize_form/1 after 2.5.0 upgrade

### ISSUE THREAD

**Issue by vitalis** [phoenixframework/phoenix_html#66]
Hi, after upgrading to 2.5.0 we have the following issue

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.normalize_form/1

        (phoenix_html) lib/phoenix_html/form.ex:239: Phoenix.HTML.Form.normalize_form(%{__struct__: Phoenix.HTML.Form, errors: [], hidden: [], id: "account", impl: Phoenix.HTML.FormData.Ecto.Changeset, index: nil, model: %ApprimeReactor.Account{__meta__: #Ecto.Schema.Metadata<:built>, company_name: nil, email: nil, encrypted_password: nil, first_name: nil, id: nil, inserted_at: nil, last_name: nil, password: nil, updated_at: nil}, name: "account", options: [method: "post", class: "form-horizontal"], params: %{}, source: %Ecto.Changeset{action: nil, changes: %{}, constraints: [%{constraint: "accounts_email_index", field: :email, message: "has already been taken", type: :unique}], errors: [], filters: %{}, model: %ApprimeReactor.Account{__meta__: #Ecto.Schema.Metadata<:built>, company_name: nil, email: nil, encrypted_password: nil, first_name: nil, id: nil, inserted_at: nil, last_name: nil, password: nil, updated_at: nil}, optional: [:company_name], opts: [], params: nil, prepare: [], repo: nil, required: [:email, :first_name, :last_name, :password], types: %{company_name: :string, email: :string, encrypted_password: :string, first_name: :string, id: :id, inserted_at: Ecto.DateTime, last_name: :string, password: :string, updated_at: Ecto.DateTime}, valid?: false, validations: [password: {:length, [min: 8]}, email: {:format, ~r/@/}]}})

        (phoenix_html) lib/phoenix_html/form.ex:234: Phoenix.HTML.Form.form_for/4
```

**Comment by josevalim** [comment]
It is an Elixir bug that has been recently fixed, `mix deps.clean phoenix_ecto` should fix it.

**Comment by vitalis** [comment]
Thank you @josevalim !!!

**Comment by tjgillies** [comment]
Can we get a link to the issue/PR? I'm curious

**Comment by ugifractal** [comment]
thanks you. mix deps.clean phoenix_ecto then mix deps.clean fixed
