### ISSUE TITLE
validate_confirmation: FunctionClauseError with  Gettext.dngettext/6

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_html#87]
I made a user registration form, following the explanation in the Phoenix book.

My registration template looks like this:

```
%h1
  = gettext("Register")
- form_for @changeset, user_path(@conn, :create), [class: "ui form"], fn f ->
  .field
    = label f, :email
    = text_input f, :email, placeholder: "my@email.com"
    = error_tag f, :email
  .field
    = label f, :password
    = password_input f, :password, placeholder: "••••••••••"
    = error_tag f, :password
  .field
    = label f, :password_confirmation
    = password_input f, :password_confirmation, placeholder: "••••••••••"
    = error_tag f, :password_confirmation

  .field
    = submit "Submit", class: "primary button"
```

The Ecto model's registration_changeset function has, among other things (following the book), a `validate_confirmation(:password)` function.

The happy path works fine. However, if someone enters a wrong value in the `password_confirmation` field, Phoenix crashes with the following error:

```
    ** (FunctionClauseError) no function clause matching in Gettext.dngettext/6
        (gettext) lib/gettext.ex:554: Gettext.dngettext(Heads.Gettext, "errors", "does not match confirmation", "does not match confirmation", nil, %{})
        (heads) web/views/error_helpers.ex:13: Heads.ErrorHelpers.error_tag/2
        (heads) web/templates/user/new.html.haml:18: anonymous fn/1 in Heads.UserView.new.html/1
        (phoenix_html) lib/phoenix_html/form.ex:235: Phoenix.HTML.Form.form_for/4
        (heads) web/templates/user/new.html.haml:4: Heads.UserView."new.html"/1
        (heads) web/templates/layout/app.html.eex:36: Heads.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (heads) web/controllers/user_controller.ex:1: Heads.UserController.action/2
        (heads) web/controllers/user_controller.ex:1: Heads.UserController.phoenix_controller_pipeline/2
        (heads) lib/phoenix/router.ex:261: Heads.Router.dispatch/2
        (heads) web/router.ex:1: Heads.Router.do_call/2
        (heads) lib/heads/endpoint.ex:1: Heads.Endpoint.phoenix_pipeline/1
        (heads) lib/plug/debugger.ex:93: Heads.Endpoint."call (overridable 3)"/2
        (heads) lib/phoenix/endpoint/render_errors.ex:34: Heads.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```
`web/views/error_helpers.ex` is a file that Phoenix/Phoenix.HTML builds when a new project is made. It turns out that the `translate_error` function uses `Gettext.dngettext/6` internally, but in the case of a confirmation error, the `opts[:count]` parameter is not set to a numeric value.

So in that file, I changed

```
  def translate_error({msg, opts}) do
    # Because error messages were defined within Ecto, we must
    # call the Gettext module passing our Gettext backend. We
    # also use the "errors" domain as translations are placed
    # in the errors.po file. On your own code and templates,
    # this could be written simply as:
    #
    #     dngettext "errors", "1 file", "%{count} files", count
    #
    Gettext.dngettext(Heads.Gettext, "errors", msg, msg, opts[:count], opts)
  end
```

to 

```
  def translate_error({msg, opts}) do
    # Because error messages were defined within Ecto, we must
    # call the Gettext module passing our Gettext backend. We
    # also use the "errors" domain as translations are placed
    # in the errors.po file. On your own code and templates,
    # this could be written simply as:
    #
    #     dngettext "errors", "1 file", "%{count} files", count
    #
    Gettext.dngettext(Heads.Gettext, "errors", msg, msg, opts[:count] || 1, opts)
  end
```

Which resolves the problem.

I am not entirely sure if this is the correct approach (Maybe this breaks error tags?), which is why I haven't made a Pull-Request for it yet.

**Comment by josevalim** [comment]
It seems you are trying latest Ecto? If so you will need to update your translate_error to this: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/web/views/error_helpers.ex#L20

**Comment by Qqwy** [comment]
Yes, that is the case. I expect this happened because this Phoenix app was made before switching over to Ecto 2.
