### ISSUE TITLE
Ecto.changeset form_for failure

### ISSUE THREAD

**Issue by OvermindDL1** [phoenixframework/phoenix_html#88]
I have this form:
```eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :perm_name, class: "control-label" %>
    <%= text_input f, :perm_name, class: "form-control", disabled: true %>
    <%= error_tag f, :perm_name %>
  </div>
<!-- deleted rest as testing, still not help -->
  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
```

And the change set it passed in via:
```elixir
Permission.changeset(%Permission{uid: uid, perm_name: name, perm: []})
```

And I am getting the stacktrace of:
```elixir
     ** (UndefinedFunctionError) undefined function Ecto.Changeset.render/2
     stacktrace:
       (ecto) Ecto.Changeset.render([perm: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #TestServer.User.Permission<>, valid?: true>], %{view_module: Ecto.Changeset, view_template: [perm: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #TestServer.User.Permission<>, valid?: true>]})
       (test_server) web/templates/auth/permissions/form.html.eex:1: TestServer.Auth.PermissionsView."form.html"/1
       (test_server) web/templates/auth/permissions/new.html.eex:3: TestServer.Auth.PermissionsView."new.html"/1
       (test_server) web/templates/layout/app.html.eex:32: TestServer.LayoutView."app.html"/1
       (phoenix) lib/phoenix/view.ex:336: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:630: Phoenix.Controller.do_render/4
       (test_server) web/controllers/auth/permissions_controller.ex:41: TestServer.Auth.PermissionsController.new/2
```

And the schema is:
```elixir
defmodule TestServer.User.Permission do
  use TestServer.Web, :model

  require Logger

  @primary_key false
  schema "user_permissions" do
    field :uid, :integer, primary_key: true
    field :perm_name, :string, primary_key: true
    field :perm, {:array, :map}

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params) do
    struct
    |> cast(params, [:uid, :perm_name, :perm])
    |> validate_required([:uid, :perm_name, :perm])
  end
end
```

So...what is causing it to call Ecto.Changeset.render/2?

Using latest :phoenix "~> 1.2.0-rc" and :phoenix_html "~> 2.5".

**Comment by josevalim** [comment]
It is pretty hard to say from what you have given us. Can you reproduce the error in a sample application?

**Comment by OvermindDL1** [comment]
Trying to reduce it currently but now I am unable to, even tried rolling back the code...  I'll leave this open for the moment, but if I am unable to reproduce it again by the time I leave work then I'll close it.
